version: "3.1"

services:
  app-prod:
    container_name: website-diabelogue-prod
    image: website-diabelogue-prod
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "80:80"
